# We will see how to read and write .txt file using numpy

In [1]:
import numpy as np

ary=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
ary

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Here we will write our data in .txt file

In [2]:
np.savetxt("text.txt",ary)

Here we will read our data from .txt file

In [3]:
txt=np.loadtxt("text.txt")
print(txt)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
