# Starting our NumPy Tutorial

In [1]:
import numpy as np
myary=np.array([1,2,3,4,5,6])
myary

array([1, 2, 3, 4, 5, 6])

In [2]:
print(myary[0],myary[1],myary[4])

1 2 5


In [3]:
myary.dtype

dtype('int32')

In [4]:
# this will gave me the size of array
myary.shape

(6,)

Here we will see the 2D array

In [5]:
myary2=np.array([[1,2,3,4,5,6]])
myary2

array([[1, 2, 3, 4, 5, 6]])

In [6]:
myary2[0]

array([1, 2, 3, 4, 5, 6])

In [10]:
#  0 row 2 index
myary2[0][2]

3

In [12]:
# 2nd method
#  0 row 2 index
myary2[0,2]

3

In [15]:
# 1 row and 6 coloumns
myary2.shape

(1, 6)