# in this tutorial we will see how to handle axies in numpy

we have row at axies 0 and coloums at axies 1


In [1]:
import numpy as np

n=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

ary=np.array(n)
ary

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [2]:
# this will sum row wise
# row down
# add row down wise (vertical row)
ary.sum(axis=0)

array([15, 18, 21, 24])

In [3]:
# this will column row wise 
# row right
# add row right wise (horizental row)
ary.sum(axis=1)

array([10, 26, 42])

We will transpose an array

In [4]:
ary

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
ary.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [6]:
ary.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
ary.flat

In [8]:
for value in ary.flat:
    print(value)

1
2
3
4
5
6
7
8
9
10
11
12


In [9]:
ary

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
ary.size

12

In [11]:
# return the index at which i have maximum value
ary.argmax()

11

In [19]:
a=[[5,2,1,3,6,4]]
arry=np.array(a)
arry

array([[5, 2, 1, 3, 6, 4]])

In [20]:
arry.argmax()
# maximum value at index '4' is '6'

4

In [22]:
arry.argmin()
# minimum value at index '2' is '1'

2

In [23]:
ary

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
np.where(ary>7)

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))