# In this tutorial we will learn how to auto-genrate an array

In [1]:
import numpy as np
zero_ary=np.zeros((8,5))
zero_ary

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
zero_ary.size

40

In [3]:
zero_ary.shape

(8, 5)

To creat one dimansional aray 


In [4]:
range_ary=np.arange(0,16)
range_ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

It will gave me eqaly spaced element of my range

 np.linspace(start,end,no_of_elements)

In [5]:
lins_arry=np.linspace(1,15,5)
lins_arry

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [6]:
lins_arry=np.linspace(1,10,10)
lins_arry

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
lins_arry=np.linspace(1,50,5)
lins_arry

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

array genrate with some items

In [14]:
emp_ary=np.empty((8,5))
emp_ary

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Genrate an 'Identity' matrix(array)

In [18]:
# it takes one argument becos it gave nxn means square array (5x5)
identity_ary=np.identity(5)
identity_ary

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
identity_ary.shape

(5, 5)

Here we will see how we can reshape an array

In [20]:
range_ary=np.arange(0,16)
range_ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
# total valyues 16 so we could make (4x4),(8x2)
range_ary.reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
reshape_ary=range_ary.reshape(2,8)
reshape_ary

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

to make multi dimension array into single dimension

In [29]:
reshape_ary.shape

(2, 8)

In [30]:
oned_ary=reshape_ary.ravel()
oned_ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
oned_ary.shape

(16,)