We will see some more basic funtions of array

In [1]:
import numpy as np


ary1=np.array([1,2,3,4,5])
ary1

array([1, 2, 3, 4, 5])

In [2]:
# print the dimension of an array
ary1.ndim

1

In [3]:
ary2=np.array([[1,2,3,4,5],[6,7,5,6,8]])
ary2

array([[1, 2, 3, 4, 5],
       [6, 7, 5, 6, 8]])

In [4]:
ary2.ndim

2

In [5]:
ary=np.arange(15)
ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
ary.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

we can creat a randome array with our chiced size and dimention or size

In [7]:
ary=np.arange(12).reshape(3,4)
ary

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])